### PR TITLE
added mkSlice function as helper to template, to be able to create slices

### PR DESCRIPTION
**Pull request by zactimeinc**
slices in templates will allow for dry-er terraform configs

adopted from https://stackoverflow.com/questions/25012467/golang-templates-how-to-define-array-in-a-variable

### CODE REVIEW

**Comment by cjmurphy42** [comment]
looks good tested with simple template `{{ $slice := mkSlice "bucket1" "bucket2" "bucket3" }}
{{ range $index, $path := $slice }}
resource "aws_s3_bucket" "{{$index}}_pixel_bucket" {
   bucket = "{{$path}}-pixel-bucket"
   acl = "private"
}
{{ end }}
`

**Comment by cjmurphy42** [comment]
looks good, should we add something to the docs? https://github.com/TimeIncOSS/ape-dev-rt/blob/master/docs/internals.md#go-templates

**Comment by zactimeinc** [comment]
Thanks for that @cjmurphy42

**Comment by zactimeinc** [comment]
@pmacey thoughts or concerns?

**Comment by pmacey** [comment]
Looks good to me, no concerns here - should be a really good feature for go template usage. I guess we can add functions to the `funcMap` declaration later if we decide to extend the template processing

**Pull request merged**
